### ISSUE TITLE
FTBFS with nim 2.2.0

### ISSUE THREAD

**Issue by micwoj92** [levovix0/DMusic#33]
**Describe the bug**
Software fails to build with nim 2.2.0

**To Reproduce**
1. Execute `nimble build -yd:release` with nim 2.2.0
2. Build fails with error:
```
   Building DMusic/dmusic using cpp backend
/build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp: In function ‘void setLen__guiZqt_u363(tySequence__rJ9bUAe0yPgTTSQSt2LrRiQ&, NI)’:
/build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp:16735:63: error: ambiguous overload for ‘operator=’ (operand types are ‘QUrl’ and ‘<brace-enclosed initializer list>’)
16735 |                                         (*(*xu).p).data[i] = {};
      |                                                               ^
In file included from /usr/include/qt/QtCore/QUrl:1,
                 from /build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp:16:
/usr/include/qt/QtCore/qurl.h:178:11: note: candidate: ‘QUrl& QUrl::operator=(const QUrl&)’
  178 |     QUrl &operator =(const QUrl &copy);
      |           ^~~~~~~~
/usr/include/qt/QtCore/qurl.h:183:11: note: candidate: ‘QUrl& QUrl::operator=(const QString&)’
  183 |     QUrl &operator=(const QString &url);
      |           ^~~~~~~~
/usr/include/qt/QtCore/qurl.h:187:18: note: candidate: ‘QUrl& QUrl::operator=(QUrl&&)’
  187 |     inline QUrl &operator=(QUrl &&other) noexcept
      |                  ^~~~~~~~
Error: execution of an external compiler program 'g++ -c -std=gnu++17 -funsigned-char  -w -fmax-errors=3 -fpermissive -pthread -I/usr/include/qt -fPIC -I/usr/include/qt/QtCore -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtQuick -I/usr/include/qt/QtQml -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtQuickControls2 -I/usr/include/qt/QtSvg -I/usr/include/qt/QtDBus -I/usr/include/taglib -O3 -fno-strict-aliasing -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/build/dmusic/src/DMusic-master/src -o /build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp.o /build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp' failed with exit code: 1


       Tip: 275 messages have been suppressed, use --verbose to show them.
nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: DMusic
```

**Expected behavior**
Successful build

**Screenshots**
N/A

 - OS: Arch Linux
 - Version dmusic: ce2fd4ce067362505e499e2028578c22b67d97ce
- version nim 2.2.0

**Additional context**
Here the  build log with `--verbose`
```   Building DMusic/dmusic using cpp backend
  Executing /usr/bin/nim cpp --colors:off --noNimblePath -d:release -d:NimblePkgVersion=0.4.1 --path:/build/.nimble/pkgs2/localize-0.3.2-9c71d11cbaea456589add01b61368df9e21c617b --path:/build/.nimble/pkgs2/nimsimd-1.3.1-06bdef255adc88a52c906819227645063e0a5661 --path:/build/.nimble/pkgs2/vmath-2.0.0-c90a664f3425d26219e1262ed9a888b859b3127c --path:/build/.nimble/pkgs2/bumpy-1.1.2-acc789c4e31b3ee969a13dd0c238d808f39b19c7 --path:/build/.nimble/pkgs2/zippy-0.10.16-da3bb5ea388f980babcc29760348e2899d29a639 --path:/build/.nimble/pkgs2/checksums-0.2.1-d3c7a1d0c0dee8fa089bd7f4d474e005877b608a --path:/build/.nimble/pkgs2/impl-0.1.0-f5356e5664bfb10fc712a584a36f3709dab48756 --path:/build/.nimble/pkgs2/filetype-0.9.0-d2242b94eeb0f6d3810a8c71af4664f28853e1be --path:/build/.nimble/pkgs2/fusion-1.2-408bde8679bce63dfb6f424e107eb37c5eb31510 --path:/build/.nimble/pkgs2/crunchy-0.1.11-d34f03fc0f6876dbf53f99601096728ec31f47a3 --path:/build/.nimble/pkgs2/chroma-0.2.7-f873f4b97e87a82e27e0b85bf9130fe3e320a2b8 --path:/build/.nimble/pkgs2/cligen-1.7.8-1261a00456f7837bd34eefa24f4f13c0fc9a6545 --path:/build/.nimble/pkgs2/pixie-5.0.7-64999611cd1093e28b62ed80e695783839441538 --path:/build/.nimble/pkgs2/flatty-0.3.4-5775e6ea6ca339efc5bd37b082b8294342d49dc5 --colors:off -o:/build/dmusic/src/DMusic-master/dmusic /build/dmusic/src/DMusic-master/src/dmusic.nim
Hint: used config file '/etc/nim/nim.cfg' [Conf]
Hint: used config file '/etc/nim/config.nims' [Conf]
Hint: used config file '/build/dmusic/src/DMusic-master/src/config.nims' [Conf]
..............................................................................................................................................................................................................................................................................
/build/dmusic/src/DMusic-master/src/gui/remotePlayer.nim(174, 22) Hint: 'p' is declared but not used [XDeclaredButNotUsed]
/build/dmusic/src/DMusic-master/src/gui/remotePlayer.nim(199, 14) Hint: 'Seeked' is declared but not used [XDeclaredButNotUsed]
.......................
CC: qrc_qml.qrc
CC: ../../../../../usr/lib/nim/system/exceptions.nim
CC: ../../../../../usr/lib/nim/system/ctypes.nim
CC: ../../../../../usr/lib/nim/std/private/digitsutils.nim
CC: ../../../../../usr/lib/nim/std/assertions.nim
CC: ../../../../../usr/lib/nim/std/formatfloat.nim
CC: ../../../../../usr/lib/nim/system/dollars.nim
CC: ../../../../../usr/lib/nim/std/syncio.nim
CC: ../../../../../usr/lib/nim/system.nim
CC: ../../../../../usr/lib/nim/pure/parseutils.nim
CC: ../../../../../usr/lib/nim/pure/bitops.nim
CC: ../../../../../usr/lib/nim/pure/math.nim
CC: ../../../../../usr/lib/nim/pure/algorithm.nim
CC: ../../../../../usr/lib/nim/pure/unicode.nim
CC: ../../../../../usr/lib/nim/pure/strutils.nim
CC: ../../../../../usr/lib/nim/pure/pathnorm.nim
CC: ../../../../../usr/lib/nim/std/oserrors.nim
CC: ../../../../../usr/lib/nim/posix/posix.nim
CC: ../../../../../usr/lib/nim/std/private/oscommon.nim
CC: ../../../../../usr/lib/nim/std/private/ospaths2.nim
CC: ../../../../../usr/lib/nim/std/private/ossymlinks.nim
CC: ../../../../../usr/lib/nim/pure/options.nim
CC: ../../../../../usr/lib/nim/pure/times.nim
CC: ../../../../../usr/lib/nim/std/private/osfiles.nim
CC: ../../../../../usr/lib/nim/std/private/osdirs.nim
CC: ../../../../../usr/lib/nim/std/envvars.nim
CC: ../../../../../usr/lib/nim/std/private/osappdirs.nim
CC: ../../../../../usr/lib/nim/std/cmdline.nim
CC: ../../../../../usr/lib/nim/pure/os.nim
CC: ../../../../../usr/lib/nim/pure/strformat.nim
CC: ../../../../../usr/lib/nim/pure/collections/sequtils.nim
CC: ../../../../../usr/lib/nim/pure/hashes.nim
CC: ../../../../../usr/lib/nim/pure/collections/tables.nim
CC: ../../../../.nimble/pkgs2/fusion-1.2-408bde8679bce63dfb6f424e107eb37c5eb31510/fusion/matching.nim
CC: ../../../../../usr/lib/nim/pure/collections/sets.nim
CC: gui/qt/smartptrs.nim
CC: gui/qt/core.nim
CC: gui/qt.nim
CC: ../../../../../usr/lib/nim/pure/streams.nim
CC: ../../../../../usr/lib/nim/pure/lexbase.nim
CC: ../../../../../usr/lib/nim/pure/parsejson.nim
CC: ../../../../../usr/lib/nim/pure/json.nim
CC: ../../../../.nimble/pkgs2/localize-0.3.2-9c71d11cbaea456589add01b61368df9e21c617b/localize.nim
CC: utils.nim
CC: gui/configuration.nim
CC: ../../../../../usr/lib/nim/pure/collections/heapqueue.nim
CC: ../../../../../usr/lib/nim/pure/collections/deques.nim
CC: ../../../../../usr/lib/nim/pure/asyncfutures.nim
CC: ../../../../../usr/lib/nim/pure/asyncstreams.nim
/build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp: In function ‘void setLen__guiZqt_u363(tySequence__rJ9bUAe0yPgTTSQSt2LrRiQ&, NI)’:
/build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp:16735:63: error: ambiguous overload for ‘operator=’ (operand types are ‘QUrl’ and ‘<brace-enclosed initializer list>’)
16735 |                                         (*(*xu).p).data[i] = {};
      |                                                               ^
In file included from /usr/include/qt/QtCore/QUrl:1,
                 from /build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp:16:
/usr/include/qt/QtCore/qurl.h:178:11: note: candidate: ‘QUrl& QUrl::operator=(const QUrl&)’
  178 |     QUrl &operator =(const QUrl &copy);
      |           ^~~~~~~~
/usr/include/qt/QtCore/qurl.h:183:11: note: candidate: ‘QUrl& QUrl::operator=(const QString&)’
  183 |     QUrl &operator=(const QString &url);
      |           ^~~~~~~~
/usr/include/qt/QtCore/qurl.h:187:18: note: candidate: ‘QUrl& QUrl::operator=(QUrl&&)’
  187 |     inline QUrl &operator=(QUrl &&other) noexcept
      |                  ^~~~~~~~
CC: ../../../../../usr/lib/nim/std/monotimes.nim
CC: ../../../../../usr/lib/nim/pure/nativesockets.nim
CC: ../../../../../usr/lib/nim/pure/dynlib.nim
CC: ../../../../../usr/lib/nim/wrappers/openssl.nim
CC: ../../../../../usr/lib/nim/pure/ssl_certs.nim
CC: ../../../../../usr/lib/nim/pure/net.nim
Error: execution of an external compiler program 'g++ -c -std=gnu++17 -funsigned-char  -w -fmax-errors=3 -fpermissive -pthread -I/usr/include/qt -fPIC -I/usr/include/qt/QtCore -I/usr/include/qt/QtGui -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtQuick -I/usr/include/qt/QtQml -I/usr/include/qt/QtMultimedia -I/usr/include/qt/QtQuickControls2 -I/usr/include/qt/QtSvg -I/usr/include/qt/QtDBus -I/usr/include/taglib -O3 -fno-strict-aliasing -fno-ident -fno-math-errno   -I/usr/lib/nim/lib -I/build/dmusic/src/DMusic-master/src -o /build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp.o /build/.cache/nim/dmusic_r/@m..@s..@s..@s..@s..@susr@slib@snim@ssystem.nim.cpp' failed with exit code: 1


nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: DMusic
     Info:  Nimble data file "/build/.nimble/nimbledata2.json" has been saved.
```

**Comment by levovix0** [comment]
should be fixed with https://github.com/levovix0/DMusic/commit/6afba9b6ff914d465d0904a83b6c0ba5d79caaaf

**Comment by micwoj92** [comment]
Thanks
